singleQuote: true
printWidth: 100
tabWidth: 2
useTabs: false
trailingComma: none
bracketSpacing: false
bracketSameLine: false
semi: false
arrowParens: avoid
singleAttributePerLine: false
endOfLine: lf
plugins:
  - prettier-plugin-curly
